### ISSUE TITLE
Crash when inspecting texture

### ISSUE THREAD

**Issue by bkaradzic** [imccown/Dissector#1]
Repro:
- launch bgfx example 01-cubes
- capture
- in first draw call after clear call (4. DrawIndexedPrimitive), double-click to inspect Texture 0.

UI displays texture preview that looks like thin texture, but pointer is NULL.

**Comment by imccown** [comment]
Fixed in R4. Was caused because texture was null. Also fixed the problem that was showing thumbnails for NULL textures if that texture slot has been used in a previously viewed draw call.
